### ISSUE TITLE
Create custom interval polling

### ISSUE THREAD

**Issue by martijnvwezel** [martijnvwezel/watermeter-esphome#2]
Using a yaml config changing the update time. Because you do not want so sent updates faster than a second. The yaml file only needs seconds and not seconds.  

How yaml should look:

``` yaml

globals:
  - id: polling_time_sec
    type: int
     # 5*60 = 5min
    initial_value: "300"

```
