### ISSUE TITLE
New Diehl Watermeter incompatible?

### ISSUE THREAD

**Issue by VDRainer** [martijnvwezel/watermeter-esphome#60]
# Problem/Motivation

After a new water meter was installed at my home, i get absolute no values anymore.
The old Watermeter worked for over a year (not 100% acurate) without problems.

Now i just want to know if the spinning disk in the new meter is incompatible and i can stop tinkering with muino, or if there's a chance to get it working.

Old Meter worked:
![20250112_094711](https://github.com/user-attachments/assets/fe84f5ff-9df9-48bc-a2f3-e7c3143b3a27)

New Meter no values at all:
![20250112_094756](https://github.com/user-attachments/assets/067834b9-5c81-4ed8-a62d-c50645756925)

I tried version 3.0.0 and 3.0.4, but simply no chance to get a value.

A few debug_json values i copied with 3.0.4  look like some data changes, but i have no clue how to deal with it. :cry: 
```
{"liters":1,"phase":5,"last_reported_liters":1,"last_reported_liters__mili":1833,"aa":95,"bb":115,"cc":70,"max_a":255,"max_b":207,"max_c":243,"min_a":10,"min_b":16,"min_c":12,"upper_bound":1500,"lower_bound":5}
{"liters":0,"phase":5,"last_reported_liters":0,"last_reported_liters__mili":833,"aa":177,"bb":188,"cc":93,"max_a":506,"max_b":318,"max_c":301,"min_a":6,"min_b":14,"min_c":10,"upper_bound":1500,"lower_bound":5}
{"liters":0,"phase":5,"last_reported_liters":0,"last_reported_liters__mili":833,"aa":122,"bb":194,"cc":94,"max_a":506,"max_b":318,"max_c":301,"min_a":6,"min_b":14,"min_c":10,"upper_bound":1500,"lower_bound":5}
```

Thanks in advance for reading this!

**Comment by martijnvwezel** [comment]
Latest version 4.0.0 has a offset value that you can set statically: https://github.com/martijnvwezel/watermeter-esphome/pull/61

The moment you find a better zero -crossing line:

![image](https://github.com/user-attachments/assets/e5e5cfaf-c76f-4abb-abe1-d4d90238171b)


you can update the parameters and it uses that  and will not change anymore

**Comment by martijnvwezel** [comment]
in your situation I need a bit more info if you want my help see the wiki: https://github.com/martijnvwezel/watermeter-esphome/wiki

**Comment by martijnvwezel** [comment]
btw first 2 liters are never shown :)

**Comment by martijnvwezel** [comment]
With https://watermeter.muino.nl/ you can update your meter to the latest or wait for your HA to tell you this. But after that you can make static values as shown above

**Comment by VDRainer** [comment]
Hi @martijnvwezel , thanks for your fast response and your tips. :+1: 

I must say, i was a little bit confused about your instructions.

What i found out in other issues with some example data:
- the sensor.debug_json has to be recorded in the (influx) database
- export some timeframe of that data to a csv file
- import that csv file in your CSV Visualizer

I don't use influxdb and dont want to install it just for debugging, so i tinkered with another solution to get the data.
1. Create a [file notification](https://www.home-assistant.io/integrations/file#notifications)
2. Create an automation that saves the state of the debug_json sensor to that file.
```
automation:
  - alias: muino_debug_json_logger
    mode: queued
    trigger:
      - platform: state
        entity_id: sensor.debug_json
        variables:
          the_json: >
            {{ (trigger.to_state.state|to_json(ensure_ascii=True)).replace("\\", "\"") }}
    action:
      - service: notify.send_message
        data:
          # entity_id,state,last_changed
          message: "sensor.debug_json,\
                    {{ the_json }},\
                    {{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
        target:
          entity_id: notify.muino_debug_json
```
Now, the json is recorded in a file and all you have to do is copy that file (or parts of it) to your local computer,
add the csv header `entity_id,state,last_changed` in the first line,
and then import it in https://watermeter.muino.nl/data_visualiser.html

If i look at values i recorded, i think i have to experiment with the mount for the sensoror on my meter?
Maybe you can say something about it?
[muino_debug_json.csv](https://github.com/user-attachments/files/18399939/muino_debug_json.csv)
